name: curvature
channels:
  - anaconda
  - soumith
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - ffmpeg=5.0.1
  - matplotlib=3.6.2
  - numpy=1.23.0
  - pip=22.1.2
  - pytorch=1.12.0
  - scipy=1.8.1
  - setuptools=63.1.0
  - toml=0.10.1
  - scikit-learn=1.1.1
  - keras==2.9.0
